# Generated by Django 4.0.6 on 2022-07-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allchars',
            options={'ordering': ['id'], 'verbose_name': 'Персонаж', 'verbose_name_plural': 'Персонажи'},
        ),
        migrations.AlterModelOptions(
            name='episodes',
            options={'ordering': ['episode'], 'verbose_name': 'Эпизод', 'verbose_name_plural': 'Эпизоды'},
        ),
        migrations.RenameField(
            model_name='episodes',
            old_name='id_char',
            new_name='chars',
        ),
        migrations.AlterField(
            model_name='allchars',
            name='created',
            field=models.DateTimeField(blank=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='allchars',
            name='gender',
            field=models.CharField(blank=True, max_length=20, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='allchars',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='allchars',
            name='location',
            field=models.JSONField(blank=True, verbose_name='Место обитания'),
        ),
        migrations.AlterField(
            model_name='allchars',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='allchars',
            name='origin',
            field=models.JSONField(blank=True, verbose_name='Происхождение'),
        ),
        migrations.AlterField(
            model_name='allchars',
            name='species',
            field=models.CharField(blank=True, max_length=50, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='allchars',
            name='status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='allchars',
            name='type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='allchars',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL адрес'),
        ),
        migrations.AlterField(
            model_name='episodes',
            name='episode',
            field=models.CharField(max_length=250, verbose_name='Эпизод'),
        ),
    ]
